### ISSUE TITLE
Security enhancement

### ISSUE THREAD

**Issue by Vebryn** [nebrius/raspi-gpio#5]
Hi,

I'm using raspi-gpio with node-red and node-red-contrib-gpio. I start node-red as root because wiringPiSetup require privileges. Is there a way to avoid starting node-red as root ? For example, by using sudo

Thank you :)

**Comment by nebrius** [comment]
Hi Vebryn, thanks for writing in! You can use `sudo` to start your scripts, that's how I usually do it myself. 

We do require root privileges for the process, whether run as user root or via sudo, because [Wiring Pi](http://wiringpi.com/), the library that underpins much of raspi-io, requires it. Unfortunately this is outside of my control, so there's not much I can do about it :-/.

Does that answer your question?
