### ISSUE TITLE
pins stay open indefinitely after instantiation

### ISSUE THREAD

**Issue by boneskull** [nebrius/raspi-gpio#7]
Example which illustrates the problem:

```js
const {DigitalInput} = require('raspi-gpio');
const input = new DigitalInput('GPIO4');
setInterval(() => {
  require('fs').writeSync(1, '.');
}, 1000).unref();
```

The following code simply exits:
```js
const {DigitalInput} = require('raspi-gpio');
// const input = new DigitalInput('GPIO4');
setInterval(() => {
  require('fs').writeSync(1, '.');
}, 1000).unref();
```

I'm not sure when this started happening, but tested it with Node 6 and Node 8 already.

The issue is due to `pigpio`'s `enableInterrupt()` called without a corresponding `disableInterrupt()`.  This likely goes for `DigitalOutput` as well.

Suggested solutions:

1.  Document that users need to call `input.input.disableInterrupt()` once they are finished with the `DigitalInput` object.
2.  Provide a `destroy()` method which calls the above method for a user, and document that instead.  :smile:
3.  Don't call `enableInterrupt()` in the constructor, and instead change the API to something like:
    ```js
    const input = new DigitalInput('GPIO4');
    const offChange = input.onChange(myChangeHandler);
    // some time later
    offChange();
    ```
    Where `DigitalInput.prototype.onChange` would call `enableInterrupt()`, and return a function (`offChange`) which would call `disableInterrupt()`.
4.  Leverage some sort of RxJS-like lib with Observables to do number 3 instead (this is a pretty strong use case for Observables!)

I'm happy to help with a PR, but would appreciate some direction.  Until then, I can work around the issue using the method in solution 1.

**Comment by nebrius** [comment]
Sorry, just now seeing this. So here's my thoughts on the above options:

1) `input.input` is a private undocumented property and _shouldn't_ be accessible. Looking at the compiled output I can see it actually is though, so I'll need to tweak the build process to mark it as truly private.

2) There's already a `destroy` method in the base class, however we don't extend it with a custom `destroy` method in the `DigitalInput` class. That said, see below.

3) This feels confusing to me, and I don't like the idea of providing a separate `onChange` method in conjunction with the existing `on` method.

4) I don't like observables :-P. Also, observables don't _actually_ apply here, as there is no property to observe the change on that would update on its own. The entire reason we enable interrupts in the first place is so we don't have to poll a value, which is done with a function call in pigpio (and thus is not observable).

All that said, let's back up a minute. Let's take a look at this code:

```JavaScript
const {DigitalInput} = require('raspi-gpio');
// const input = new DigitalInput('GPIO4');
setInterval(() => {
  require('fs').writeSync(1, '.');
}, 1000).unref();
```

As you mentioned, this code simply exits, which is the correct behavior.

Then there's this code:

```
const {DigitalInput} = require('raspi-gpio');
const input = new DigitalInput('GPIO4');
setInterval(() => {
  require('fs').writeSync(1, '.');
}, 1000).unref();
```

This code does not exit, as you mentioned. This is _also_ the correct behavior. To see why, consider this analogous code:

```
const http = require('http');
const server = http.createServer().listen(3000);
```

This code _also_ does not exit, even though there are no event listeners attached to the server instance. The GPIO example is the same because you're creating a thing that listens for changes, in this case changes on a GPIO pin instead of server requests. Indeed, this is the entire reason for this module's existance. So I'm sorry to say that the behavior you're seeing is a feature not a bug.

That said, I do think that we should pursue option 2) because it does expose a different bug, as shown by the following code:

```
const { init } = require('raspi'); // Don't forget this
const { DigitalInput } = require('raspi-gpio');
const { PWM } = require('raspi-pwm');

raspi.init(() => {
  const input = new DigitalInput('GPIO4');
  const pwm = new PWM('GPIO4'); // This will cause the GPIO instance to be destroyed, but interrupts remain enabled indefinitely
}
```

**Comment by nebrius** [comment]
I just published v4.1.0 of raspi-gpio that now overrides `destroy()` so that it calls `this.input.disableInterrupt()`.  Feel free to call this once you're done using GPIO so that Node.js can exit cleanly!

Feel free to reopen if you run into anymore issues!

**Comment by boneskull** [comment]
FWIW, I'm in disagreement that these two snippets are analogous:

```js
const input = new DigitalInput('GPIO4');
```

```js
const server = http.createServer().listen(3000);
```

Yes, they are analogous in the end result, but what I would expect is that `DigitalInput`'s constructor doesn't bind to a pin, like `http.createServer`:

```js
// does not bind to a port; accepts a "request" handler
const server = http.createServer(req => {
  // handle request
});
// time passes ... 
server.listen(3000);
```

In the above example, we've simply instantiated an object.   Given that there's no "destructor" in JS, I'd prefer (*my opinion*) constructors don't bind to IO resources, e.g.:

```js
// does not bind to a pin; accepts a "change" handler
const input = new DigitalInput(value => {
  // handle value
});
// time passes ... 
input.listen('GPIO4');
```

Anyway, thanks for fixing the bug!

**Comment by nebrius** [comment]
We can't do your approach though, because there are also methods on the `input` instance that work with the specified pin. I prefer keeping it in the constructor because it decreases room for bugs on the part of the user, and honestly I don't see what you gain from splitting the methods apart aside from stylistic choices. So weighing better stylistic aesthetic vs less surface area for bugs on the user's part, I always go with the latter.

Consider the following code:

```JavaScript
const input = new DigitalInput(value => {
  // handle value
});
// time passes ... 
input.read() // What does this do?
// time passes ... 
input.listen('GPIO4');
```
